FROM python:3.13-slim as builder

WORKDIR /install

COPY requirements.txt .

RUN pip install --no-cache-dir --target=/install/deps -r requirements.txt


FROM python:3.13-slim

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/deps
ENV PATH=/deps/bin:$PATH

WORKDIR /pipe

RUN useradd -m 8239

COPY --from=builder /install/deps /deps

COPY pipe/ /pipe/
COPY data/ /data/

RUN chown -R 8239:8239 /pipe /data
USER 8239

CMD ["python", "take_data.py"]